import type {
  AnalyticsView,
  EmpireView,
  FriendsView,
  LeaderboardView,
  MissionsView,
  ShopView,
} from '../game/types';

// DESIGN_PREVIEW_FIXTURE_ONLY — imported only from the DEV-gated preview entry.
export const empireFixture: EmpireView = {
  cash: 124850,
  seasonPoints: 8750,
  production: 138,
  claimable: 24840,
  offlineHours: 4,
  businesses: [
    {
      slug: 'street_stand',
      name: 'Sokak Tezgâhı',
      level: 12,
      production: 35,
      upgradeCost: 729,
      paybackSeconds: 82,
      recommended: false,
    },
    {
      slug: 'cafe',
      name: 'Köşe Kafe',
      level: 5,
      production: 103,
      upgradeCost: 5719,
      paybackSeconds: 215,
      recommended: true,
    },
    {
      slug: 'delivery_hub',
      name: 'Dağıtım Merkezi',
      level: 0,
      production: 0,
      upgradeCost: 25000,
      paybackSeconds: 278,
      recommended: false,
    },
    {
      slug: 'factory',
      name: 'Fabrika',
      level: 0,
      production: 0,
      upgradeCost: 250000,
      paybackSeconds: 417,
      recommended: false,
    },
    {
      slug: 'tech_company',
      name: 'Teknoloji Şirketi',
      level: 0,
      production: 0,
      upgradeCost: 3000000,
      paybackSeconds: 600,
      recommended: false,
    },
    {
      slug: 'global_holding',
      name: 'Global Holding',
      level: 0,
      production: 0,
      upgradeCost: 50000000,
      paybackSeconds: 834,
      recommended: false,
    },
  ],
};
export const missionsFixture: MissionsView = {
  streak: 4,
  missions: [
    {
      id: 'mission-1',
      title: 'Küçük adımlar, büyük işler',
      description: 'İşletmelerinde 3 yükseltme yap.',
      difficulty: 'easy',
      progress: 3,
      target: 3,
      reward: 300,
      status: 'completed',
    },
    {
      id: 'mission-2',
      title: 'Şehir hiç uyumaz',
      description: 'Toplam 20.000 Nakit gelir topla.',
      difficulty: 'normal',
      progress: 14200,
      target: 20000,
      reward: 400,
      status: 'in_progress',
    },
    {
      id: 'mission-3',
      title: 'Bir üst seviyeye',
      description: 'Bir işletmeni 10. seviyeye ulaştır.',
      difficulty: 'hard',
      progress: 1,
      target: 1,
      reward: 500,
      status: 'claimed',
    },
    {
      id: 'mission-4',
      title: 'Haftanın girişimcisi',
      description: 'Bu hafta 5 farklı günde şehrine dön.',
      difficulty: 'weekly',
      progress: 3,
      target: 5,
      reward: 2000,
      status: 'in_progress',
    },
  ],
};
export const friendsFixture: FriendsView = {
  link: 'https://t.me/EmpirePreviewBot?startapp=ref_DESIGN',
  totalInvites: 8,
  qualified: 3,
  earnedPoints: 2600,
  friends: [
    { name: 'Deniz', initial: 'D', stage: '7. gün tamamlandı', days: 7 },
    { name: 'Mira', initial: 'M', stage: '2. gün tamamlandı', days: 2 },
    {
      name: 'Arda',
      initial: 'A',
      stage: 'İlk işletmesini geliştirdi',
      days: 1,
    },
  ],
};
export const leaderboardFixture: LeaderboardView = {
  scope: 'global',
  seasonName: 'Yeni başlangıçlar',
  entries: [
    { rank: 1, userId: 'design-1', name: 'Atlas', points: 28450, isYou: false },
    { rank: 2, userId: 'design-2', name: 'Luna', points: 26320, isYou: false },
    { rank: 3, userId: 'design-3', name: 'Nova', points: 24900, isYou: false },
    { rank: 4, userId: 'design-4', name: 'Deniz', points: 21800, isYou: false },
    { rank: 5, userId: 'design-5', name: 'Mira', points: 19640, isYou: false },
    { rank: 6, userId: 'design-6', name: 'Ege', points: 18200, isYou: false },
  ],
  ownRank: 42,
  ownPoints: 8750,
  total: 1248,
  hasMore: true,
};
export const shopFixture: ShopView = {
  passActive: false,
  expiresAt: null,
  products: [
    {
      sku: 'convenience_pass_30d',
      name: 'Empire Pass',
      description: 'Şehrin çalışsın. Sen kendi ritminde yaşa.',
      price: 250,
      type: 'convenience_pass',
      durationDays: 30,
    },
    {
      sku: 'cosmetic_frame_gold',
      name: 'Altın Çerçeve',
      description: 'Profiline zarif bir imza bırak.',
      price: 100,
      type: 'cosmetic',
      durationDays: null,
    },
    {
      sku: 'cosmetic_emblem_founder',
      name: 'Kurucu Arması',
      description: 'İmparatorluğunun ilk günlerini hatırla.',
      price: 150,
      type: 'cosmetic',
      durationDays: null,
    },
  ],
};
export const analyticsFixture: AnalyticsView = {
  activation: 0.684,
  payerConversion: 0.042,
  revenue: 18450,
  arppu: 312,
  cohorts: [
    { date: '2026-09-01', signups: 240, d1: 0.64, d7: 0.28 },
    { date: '2026-09-02', signups: 320, d1: 0.68, d7: 0.32 },
    { date: '2026-09-03', signups: 286, d1: 0.71, d7: 0.34 },
    { date: '2026-09-04', signups: 412, d1: 0.73, d7: 0.36 },
    { date: '2026-09-05', signups: 384, d1: 0.69, d7: 0.31 },
  ],
};
